# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  identifier = "home"
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  identifier = "basic"
  name = "新手入门"
  pageRef = "basic"
  weight = 20

[[main]]
  identifier = "practice"
  name = "练习资源"
  pageRef = "practice"
  weight = 30

# [[main]]
#   identifier = "p1"
#   name = "放松冥想"
#   parent = "practice"
#   pageRef = "categories/放松冥想"
#   weight = 31

# [[main]]
#   identifier = "p2"
#   name = "专注冥想"
#   parent = "practice"
#   pageRef = "categories/专注冥想"
#   weight = 32

# [[main]]
#   identifier = "p3"
#   name = "睡眠冥想"
#   parent = "practice"
#   pageRef = "categories/睡眠冥想"
#   weight = 33

# [[main]]
#   identifier = "p4"
#   name = "行走冥想"
#   parent = "practice"
#   pageRef = "categories/行走冥想"
#   weight = 34

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  name = "课程活动"
  pageRef = "course"
  weight = 40

[[main]]
  name = "关于我们"
  pageRef = "about"
  weight = 50


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "按目标"
  pageRef = "goal"
  weight = 100

[[footer]]
  name = "按方法"
  pageRef = "method"
  weight = 80

[[footer]]
  name = "按系列"
  pageRef = "series"
  weight = 40

[[footer]]
  name = "按场景"
  pageRef = "duration"
  weight = 60

[[footer]]
  name = "按导师"
  pageRef = "authors"
  weight = 20

[[footer]]
  name = "按标签"
  pageRef = "tags"
  weight = 20
