# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  identifier = "home"
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  identifier = "basic"
  name = "Basic"
  pageRef = "basic"
  weight = 20

[[main]]
  identifier = "practice"
  name = "Practice"
  weight = 30

[[main]]
  identifier = "p1"
  name = "Relax Meditation"
  parent = "practice"
  pageRef = "categories/relax"
  weight = 31

[[main]]
  identifier = "p2"
  name = "Attention Meditation"
  parent = "practice"
  pageRef = "categories/attention"
  weight = 32

[[main]]
  identifier = "p3"
  name = "Sleeping Meditation"
  parent = "practice"
  pageRef = "categories/sleeping"
  weight = 33

[[main]]
  identifier = "p4"
  name = "Walk Meditation"
  parent = "practice"
  pageRef = "categories/walk"
  weight = 34

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  name = "Course"
  pageRef = "course"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "下载App"
  pageRef = "download"
  weight = 100
